name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Run ESLint action
        uses: stefanoeb/eslint-action@1.0.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }
        with:
          args: './res/**/*.js --max-warnings 0' 
